// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApF5_Crzz6aQyS4UlSct3dNVgp4fz_Lho',
    appId: '1:434284529245:web:b702b9d33c216b2756afb4',
    messagingSenderId: '434284529245',
    projectId: 'flutter-firebase-sample-2e54f',
    authDomain: 'flutter-firebase-sample-2e54f.firebaseapp.com',
    storageBucket: 'flutter-firebase-sample-2e54f.appspot.com',
    measurementId: 'G-5GKLBMBNQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHeN5QdOB5goMmdXjFBI4pHRgmrAgCxtE',
    appId: '1:434284529245:android:743b34a2476b23e656afb4',
    messagingSenderId: '434284529245',
    projectId: 'flutter-firebase-sample-2e54f',
    storageBucket: 'flutter-firebase-sample-2e54f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlRXyr23pBfHqjU9jckWqQt0dfZBfTiPI',
    appId: '1:434284529245:ios:8e1a8169f76cd76456afb4',
    messagingSenderId: '434284529245',
    projectId: 'flutter-firebase-sample-2e54f',
    storageBucket: 'flutter-firebase-sample-2e54f.appspot.com',
    iosClientId: '434284529245-68kr4n1c5pa10pt86a8t7eqosv4io2rb.apps.googleusercontent.com',
    iosBundleId: 'com.example.sample',
  );
}
